---
#####
# https://github.com/probot/settings/blob/master/README.md
repository:
  name: "gh-actions"
  topics: "cloud, gh-actions"
  description: "gh-actions"
  homepage: "https://github.com/nbugden/gh-actions"
  delete_branch_on_merge: true
  allow_squash_merge: true
  allow_merge_commit: false

# https://developer.github.com/v3/apps/available-endpoints/
teams:
  - name: data
    permission: admin
  - name: developers
    permission: write

branches:
  - name: main
    # https://developer.github.com/v3/repos/branches/#update-branch-protection
    # Branch Protection settings. Set to null to disable
    protection:
      # Required. Require status checks to pass before merging. Set to null to disable
      required_status_checks:
        # Required. Require branches to be up to date before merging.
        strict: true
        # Required. The list of status checks to require in order to merge into this branch
        contexts: ["Semantic Pull Request"]
      # Required. Enforce all configured restrictions for administrators. Set to true to enforce required status checks for repository administrators. Set to null to disable.
      enforce_admins: true
      # Required. Restrict who can push to this branch. Team and user restrictions are only available for organization-owned repositories. Set to null to disable.
      restrictions:
        users: []
        teams: []
