name: build

on:
  workflow_call:
    inputs:
      clutch_env:
        required: true
        type: string
      aws_default_region:
        required: true
        type: string
        default: ca-central-1
    secrets:
      github_token:
        required: true
      aws_access_key:
        required: true
      aws_secret_access_key:
        required: true

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
  infra:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: $TERRAFORM_VERSION
      - name: Terraform Init
        run: terraform -chdir=terraform init
      - name: Terraform Plan
        run: terraform -chdir=terraform plan
      - name: Terraform Apply
        run: terraform -chdir=terraform apply --auto-approve
  deploy:
    needs: infra
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}
      - name: Deploy to $CLUTCH_ENV environment
        run: |
          git branch;
          echo deploying to $CLUTCH_ENV;

env:
  CLUTCH_ENV: ${{ inputs.clutch_env }}
  GITHUB_TOKEN: ${{ secrets.github_token }}
  TERRAFORM_VERSION: 1.0.8
  TF_WORKSPACE: ${{ inputs.clutch_env }}
  TF_VAR_AWS_DEFAULT_REGION: ${{ inputs.aws_default_region }}
  TF_VAR_AWS_ACCESS_KEY_ID: ${{ secrets.aws_access_key }}
  TF_VAR_AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_access_key }}
