name: CI/CD

on: [pull_request]

jobs:
  linting:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install Requirements
        run: |
          python -m pip install --upgrade pip
          pip install pylint glob2
      - name: Run Pylint
        run: |
          python ./.github/workflows/lint.py --threshold 8.5

  dependency-security:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install safety
      - name: Test with safety
        run: |
          requirements_files=`find "." -type f -name "requirements.txt"`;
          for eachfile in $requirements_files
            do
              echo "Running Tests for: ${eachfile}"
              safety check -r ${eachfile}
            done;

  unit_tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox tox-gh-actions
      - name: Test with tox
        run: |
          tox_files=`find "." -type f -name "tox.ini"`;
          for eachfile in $tox_files
            do
              echo "Running Tests for: ${eachfile}"
              tox -c ${eachfile}
            done;

  infra:
    needs: [unit_tests, linting, dependency-security]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: $TERRAFORM_VERSION
      - name: Terraform Init
        run: terraform -chdir=terraform init
      - name: Terraform Plan
        run: terraform -chdir=terraform plan

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  TERRAFORM_VERSION: 1.0.8
