name: testing-deploy

on:
  push:
    branches: [main]

jobs:
  call-workflow-passing-data:
    uses: octo-org/example-repo/.github/workflows/workflow-B.yml@main
    secrets:
      github_token: ${{ secrets.GITHUB_TOKEN }}
